---
title: "Caring Analysis"
author: "Jonathan Luu"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
library(tidyverse)
library(lubridate)

# Read in data
dat <- read.csv("/Users/jonathanluu/Dropbox/Caring Health/Data/CHC_SDOH_dataset_1.5.22_SFTPupload.csv")

# Reformat dates
dat <- dat %>% mutate(Last_Visit_Date = mdy(Last_Visit_Date), ENC_DATE = mdy(str_remove(dat$ENC_DATE, " 0:00")))

# Create categorical visit
dat <- dat %>% mutate(cat_visit = case_when(Num_Visits <= 1 ~ 0, 
                                 Num_Visits > 1 & Num_Visits <= 3 ~ 1,
                                 Num_Visits > 3 & Num_Visits <= 10 ~ 2,
                                 Num_Visits > 10 & Num_Visits <= 25 ~ 3,
                                 Num_Visits > 25 & Num_Visits <= 50 ~ 4,
                                 Num_Visits > 50 ~ 5))

# Create categorical age
dat <- dat %>% mutate(cat_age = case_when(Age <= 32 ~ 0, 
                                 Age > 32 & Age <= 44 ~ 1,
                                 Age > 44 & Age <= 58 ~ 2,
                                 Age > 58 ~ 3))

# Get distinct IDs
dat.distinct <- dat %>% distinct(PAT_ID, .keep_all = T)
```

# Exploratory analysis - July 14, 2022

```{r}
# Number of unique entries
length(unique(dat.distinct$PAT_ID))

# Age distribution
dat.distinct$Age %>% summary()
dat.distinct$Age %>% hist(main="Histogram of age", xlab="Age (years)")

# Language
dat.distinct$Language %>% unique() %>% length() # 64 different languages spoken
dat.distinct$Language %>% table() %>% sort(decreasing = T) %>% 
  head(n=15) %>% as_tibble() %>% rename(Language=".") # Most popular languages
```

\newpage
```{r}
# Race
race.table <- dat.distinct$Race %>% table() %>% sort() %>% 
  as.data.frame() %>% rename(Race=".")
race.table %>% as_tibble()

# Race barplot
race.table %>% ggplot(aes(x=Freq, y=Race)) + geom_bar(stat="identity") +
  theme(axis.text.y=element_text(angle=0,hjust=1,vjust=0.5)) + 
  ggtitle("Race frequency")
```

\newpage
```{r}
# Ethnicity
eth.table <- dat.distinct$Ethnicity %>% table() %>% sort() %>% 
  as.data.frame() %>% rename(Ethnicity=".")
eth.table %>% as_tibble()

# Ethnicity barplot
eth.table %>% ggplot(aes(x=Freq, y=Ethnicity)) + geom_bar(stat="identity") +
  theme(axis.text.y=element_text(angle=0,hjust=1,vjust=0.5)) + 
  ggtitle("Ethnicity frequency")
```

\newpage
```{r}
# Number of visits
dat.distinct$Num_Visits %>% summary()

# Most common number of visits
dat.distinct$Num_Visits %>% table() %>% sort(decreasing=T) %>% 
  head(n=10) %>% as_tibble() %>% rename("Num Visit"=".")
dat.distinct %>% filter(Num_Visits <= 15) %>% pull(Num_Visits) %>% 
  hist(breaks=0:15, main="Histogram of number of visits", xlab="Number of visits")
```

\newpage
# Survey question descriptives

```{r}
# Response types
dat$MEAS_DISP_NAME %>% unique() %>% length() # 45 different response types
options(pillar.print_max = 50, pillar.print_min = 50)
dat$MEAS_DISP_NAME %>% table() %>% sort(decreasing=T) %>% 
  as_tibble() %>% rename(Question=".")

# Response categories
dat$DOMAIN_GRP %>% table() %>% sort(decreasing=T) %>% 
  as_tibble() %>% rename(Response=".") # 13 categories of responses

# Individuals with the most # of responses
dat$PAT_ID %>% table() %>% sort(decreasing = T) %>% head(n=10) %>% 
  as_tibble() %>% rename(ID=".")
```

\newpage
# August 14 Analysis

```{r}
# Create new dataset showing number of responses by id and encounter
dat.resp.enc <- dat %>% count(PAT_ID, DOMAIN_GRP, ENC_DATE) %>% mutate_all(na_if,"") %>%
  pivot_wider(names_from = DOMAIN_GRP, values_from = n) 

# Ranges of screening
dat.resp.enc <- dat.resp.enc %>% mutate_if(is.integer, ~replace(.,is.na(.),0))
dat.resp.enc <- dat.resp.enc %>% select(-"NA") %>% mutate(sum = rowSums(across(where(is.numeric))))

# Number of questions answered
dat.resp.enc %>% filter(sum==0) %>% select(PAT_ID) %>% unique() %>% nrow() # 21611 people did not have a survey answer
ans.n <- dat.resp.enc %>% filter(sum > 0) %>% select(PAT_ID) %>% unique() %>% nrow() # 2469 individuals who did answer

# Extract covariates for each ID
covar <- dat.distinct %>% select(PAT_ID, cat_age, cat_visit, Race, Ethnicity, Language)
dat.resp.enc <- merge(dat.resp.enc,covar,all.x=T)

# What constitutes completion? - Distribution of those who did complete a survey and how many questions did they answer?
# 1035 people answered a financial question
total.n <- dat.distinct %>% nrow()
fin.n <- nrow(dat.resp.enc %>% filter(`Financial/Other`>0) %>% select(PAT_ID) %>% unique())
fin.n/ans.n # 42% of the 2469 who answered
fin.n/total.n # 4% of the total 24080

# 2218 people answered a relationship safety question
rel.n <- nrow(dat.resp.enc %>% filter(`Relationship Safety`>0) %>% select(PAT_ID) %>% unique())
rel.n/ans.n # 90% of the 2469 who answered
rel.n/total.n # 9% of the total 24080

# People who answered all questions in these 4 categories: Housing, transportation, food, and stress
group.n <- dat.resp.enc %>% filter(sum>0)
group.n.id <- dat.resp.enc %>% select("Food Insecurity","Housing","Transportation","Stress and Social Isolation") > 0
group.n.id <- which(tibble(group.n.id) %>% apply(1,sum) == 4)
group.n <- dat.resp.enc %>% slice(group.n.id)
nrow(group.n) # 983 encounters with these 4 domain questions answered
length(unique(group.n$PAT_ID)) # 920 individuals with these 4 domain questions answered

# People who answered a question in all domains
dom.n <- dat.resp.enc %>% filter(sum>0)
dom.n.id <- dom.n %>% select(-c(PAT_ID,ENC_DATE,sum)) > 0
dom.n.id <- which(tibble(dom.n.id) %>% apply(1,sum) == 12)
dom.n <- dom.n %>% slice(dom.n.id)
nrow(dom.n) # 636 encounters with all domain questions answered
length(unique(dom.n$PAT_ID)) # 606 individuals with all domain questions answered

# How many screens are done per individual
# Assumption: A screen is when at least 1 question is answered during an encounter
screen.count <- dat.resp.enc %>% filter(sum>0) %>% count(PAT_ID)
summary(screen.count$n)
table(screen.count$n) # 2075 out of 2469 had only one screen
dat.resp.enc <- full_join(dat.resp.enc, screen.count, by="PAT_ID") %>% rename("n_encounter" = "n") # Append number of encounters to dataset

table(dat.resp.enc %>% distinct(PAT_ID, .keep_all = T) %>% select(n_encounter)) # Tabulated num of encounters
```

```{r}
# 24080 unique individuals  - all patients 18+ years old who had an encounter in the past year in an SA38 department with at least one non-voided charge
# 236450 total # of visits ranging from 1 to 268 visits per individual
# 65533 observations - mix of single observation with no SDH and 1+ observation(s) with SDH
# 21611 individuals with no SDH information
# 2469 individuals answered at least one question, 2925 encounters total
## 1035 individuals answered a financial question
## 2218 individuals answered a relationship safety question
## 920 individuals with 4 domain questions answered
## 606 individuals with all domain questions answered
```

\newpage
# September 26 Analysis

```{r}
# Individuals with more visits more likely to have at least 1 SDH screening
round(tapply(!is.na(dat.distinct$FLO_MEAS_ID), list(dat.distinct$cat_visit), FUN = mean),2)

# Older less likely to have a screening
round(tapply(!is.na(dat.distinct$FLO_MEAS_ID), list(dat.distinct$cat_age), FUN = mean),2)

# Probability of having at least 1 SDH screening by race
round(tapply(!is.na(dat.distinct$FLO_MEAS_ID), list(dat.distinct$Race, dat.distinct$Ethnicity), FUN = mean),2)

# Probability of having at least 1 SDH screening by ethnicity
round(tapply(!is.na(dat.distinct$FLO_MEAS_ID), list(dat.distinct$Ethnicity), FUN = mean),2)

round(tapply(!is.na(dat.distinct$FLO_MEAS_ID), list(dat.distinct$Language), FUN = mean),2)


# Range of dates
summary(dat.distinct$Last_Visit_Date)
summary(dat.distinct$ENC_DATE)

# Demographics of those who responded
dat.resp.distinct <- dat.resp.enc %>% filter(sum > 0) %>% distinct(PAT_ID, .keep_all = T)

# Race table of those who responded
table(dat.resp.distinct$Race)

# Ethnicity table of those who responded
table(dat.resp.distinct$Ethnicity)

# Age category table of those who responded: 0: <32, 1: 32-44, 2: 44-58, 3: >58
table(dat.resp.distinct$cat_age)

# Visit category table fo those who responded: 0: 1, 1: 1-3, 2: 3-10, 3: 10-25, 4: 25-50, 5: >50 
table(dat.resp.distinct$cat_visit)

# Visits in a year
dat.resp.distinct %>% filter(ENC_DATE >= "2018-01-01" & ENC_DATE <= "2018-12-31") %>% nrow()
dat.resp.distinct %>% filter(ENC_DATE >= "2019-01-01" & ENC_DATE <= "2019-12-31") %>% nrow()
dat.resp.distinct %>% filter(ENC_DATE >= "2020-01-01" & ENC_DATE <= "2020-12-31") %>% nrow()
dat.resp.distinct %>% filter(ENC_DATE >= "2021-01-01" & ENC_DATE <= "2021-12-31") %>% nrow()

# Talk to Sebastien about abstract / paper moving forward
# Export dat.distinct and send over sorted by date
# How much is missing in REL
```









