---
title: "Caring Health Tables"
author: "Jonathan Luu"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, comment = NA)
library(tidyverse)
library(readxl)
library(lubridate)

# Read in data
#path <- "C:\\Users\\Jonathan\\Dropbox\\Caring Health\\Data\\Caring_Data_V2.xlsx"
path <- "/Users/jonathanluu/Library/CloudStorage/Dropbox/Caring Health/Data/Caring_Data_V2.xlsx"
dat <- lapply(excel_sheets(path = path), function(x) 
  read_excel(path = path, sheet = x, col_types = c(rep("guess",20),"text","logical")))
dat <- bind_rows(dat)

# Create categorical visit
dat <- dat %>% mutate(cat_visit = case_when(num_of_visits <= 1 ~ 0, 
                                 num_of_visits > 1 & num_of_visits <= 3 ~ 1,
                                 num_of_visits > 3 & num_of_visits <= 8 ~ 2,
                                 num_of_visits > 8 ~ 3))

# Create categorical age
dat <- dat %>% mutate(cat_age = case_when(Age <= 39 ~ 0, 
                                 Age > 39 & Age <= 64 ~ 1,
                                 Age > 64 ~ 2))

# Rename some columns
dat <- rename(dat, Language = "LANGUAGE_NAME", Ethnicity = "ETHNIC_GROUP", Race = "RACE")

# Format dates
dat <- dat %>% mutate(ENC_DATE = ymd(ENC_DATE), Last_Visit_Date = ymd(Last_Visit_Date))

# Get distinct IDs
dat.distinct <- dat %>% distinct(PAT_ID, .keep_all = T)

# Create new dataset showing number of responses by id and encounter
dat.encounter <- dat %>% count(PAT_ID, DOMAIN_GRP, ENC_DATE) %>% mutate_all(na_if,"") %>%
  pivot_wider(names_from = DOMAIN_GRP, values_from = n) 
dat.encounter <- dat.encounter %>% mutate_if(is.integer, ~replace(.,is.na(.),0))
dat.encounter <- dat.encounter %>% select(-"NA") %>% mutate(sum = rowSums(across(where(is.numeric))))
covar <- dat.distinct %>% select(PAT_ID, cat_age, cat_visit, Race, Ethnicity, Language, HasChargeVisit)
dat.encounter <- merge(dat.encounter,covar,all.x=T)
screen.count <- dat.encounter %>% filter(sum>0) %>% count(PAT_ID)
dat.encounter <- full_join(dat.encounter, screen.count, by="PAT_ID") %>% rename("n_encounter" = "n") # Append number of encounters to dataset

# Create dataset of those screened
response_ids <- dat.encounter %>% filter(sum > 0) %>% distinct(PAT_ID) %>% c() %>% .[[1]]
dat.screened <- dat %>% filter(PAT_ID %in% response_ids)
dat.distinct.screened <- dat.screened %>% distinct(PAT_ID, .keep_all = T)
```

```{r}
### Table 1 - Demographics

###Patients
length(unique(dat.distinct$PAT_ID)) #32421 individuals
dat.distinct.screened %>% nrow() # 8941 screened
dat.encounter %>% filter(sum==0) %>% select(PAT_ID) %>% unique() %>% nrow() # 23480 not screened

###Preferred language
# All
dat.distinct$Language %>% table() %>% sort(decreasing = T) %>% 
  head(n=6) %>% as_tibble() %>% rename(Language=".") # Most popular languages
dat.distinct$Language %>% table() %>% sort(decreasing = T) %>% 
  .[7:(length(unique(dat.distinct$Language))-1)] %>% sum() # Other language

# Screened
dat.distinct.screened$Language %>% table() %>% sort(decreasing = T) %>% 
  head(n=6) %>% as_tibble() %>% rename(Language=".") # Most popular languages
dat.distinct.screened$Language %>% table() %>% sort(decreasing = T) %>% 
  .[7:(length(unique(dat.distinct.screened$Language))-1)] %>% sum() # Other language

### Ethnicity
# All
dat.distinct$Ethnicity %>% table() %>% as.data.frame() %>% rename(Ethnicity=".")
# Screened
dat.distinct.screened$Ethnicity %>% table() %>% as.data.frame() %>% rename(Ethnicity=".")

### Race
# All
dat.distinct$Race %>% table() %>% sort(decreasing = T) %>% as.data.frame() %>% rename(Race=".")
# Screened
dat.distinct.screened$Race %>% table() %>% sort(decreasing = T) %>%
  as.data.frame() %>% rename(Race=".")

### Age category
# All
dat.distinct$cat_age %>% table() # 0= <39, 1= 40-64, 2= >65
# Screened
dat.distinct.screened$cat_age %>% table() 

### Number of visits
# All
dat.distinct$cat_visit %>% table() # 0= 1, 1= 2-3, 2= 4-8, 3= 9+
# Screened
dat.distinct.screened$cat_visit %>% table()

### Provider type
dat$TakenProviderType %>% table() %>% sort(decreasing=T) %>% 
  as.tibble() %>% rename("Taken Provider Type"=".") 

### Screen count
screen.count$n %>% table() 
screen.count$n %>% table() %>% .[4:8] %>% sum() # 4+
```

\newpage
```{r}
### Table 2 - Screening questions

# Screening questions answered
screeningNum <- function(category){
  uniq <- dat.encounter %>% select(category, PAT_ID)
  uniq[uniq[,1]>0,] %>% distinct(PAT_ID, .keep_all=T) %>% nrow()
}
categories <- colnames(dat.encounter)[3:14]
sapply(categories, screeningNum)

# People who answered all questions in these 4 categories: Housing, transportation, food, and stress
group.n <- dat.encounter %>% filter(sum>0) 
group.n.id <- dat.encounter %>% select("Food Insecurity","Housing","Transportation","Stress and Social Isolation") > 0
group.n.id <- which(tibble(group.n.id) %>% apply(1,sum) == 4)
group.n <- dat.encounter %>% slice(group.n.id)
length(unique(group.n$PAT_ID)) # 5996 individuals with these 4 domain questions answered

# People who answered a question in all domains
dom.n <- dat.encounter %>% filter(sum>0)
dom.n.id <- dom.n %>% select(all_of(categories)) > 0
dom.n.id <- which(tibble(dom.n.id) %>% apply(1,sum) == 12)
dom.n <- dom.n %>% slice(dom.n.id)
length(unique(dom.n$PAT_ID)) # 1240 individuals with all domain questions answered

# All questions
options(pillar.print_max = 50, pillar.print_min = 50)
allQ <- dat.screened %>% distinct(PAT_ID, MEAS_DISP_NAME, .keep_all = T) %>% .$MEAS_DISP_NAME %>% table() %>% sort(decreasing=T) %>% 
  as_tibble() %>% rename(Question=".")

# Collected by
collectNum <- function(question){
  dat.screened %>% distinct(PAT_ID, MEAS_DISP_NAME, .keep_all = T) %>% 
    filter(MEAS_DISP_NAME == question) %>% .$TakenProviderType %>% 
    table() %>% sort(decreasing=T) %>% head(n=1) %>% names()
}
sapply(allQ$Question, collectNum)
```



